-- This file is for use with Corona(R) SDK
--
-- This file is automatically generated with PhysicsEdtior (http://physicseditor.de). Do not edit
--
-- Usage example:
--			local scaleFactor = 1.0
--			local physicsData = (require "shapedefs").physicsData(scaleFactor)
--			local shape = display.newImage("objectname.png")
--			physics.addBody( shape, physicsData:get("objectname") )
--

-- copy needed functions to local scope
local unpack = unpack
local pairs = pairs
local ipairs = ipairs

local M = {}

function M.physicsData(scale)
	local physics = { data =
	{ 
		
		["floor-1"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "floor-1", density = 2, friction = 0.5, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   186.5, 333.5  ,  -186.5, 333.5  ,  -135.5, 280.5  ,  186.5, 280.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "floor-1", density = 2, friction = 0.5, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -186.5, -333.5  ,  -135.5, -333.5  ,  -135.5, 280.5  ,  -186.5, 333.5  }
                    }
                    
                    
                    
		}
		
		, 
		["floor-2"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "floor-2", density = 2, friction = 0.5, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -617.5, -25.5  ,  617.5, -25.5  ,  617.5, 25.5  ,  -617.5, 25.5  }
                    }
                    
                    
                    
		}
		
		, 
		["floor-3"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "floor-3", density = 2, friction = 0.5, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   373.5, 66.5  ,  -373.5, 66.5  ,  136.5, -52.5  ,  275.5, -65.5  ,  373.5, -66.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "floor-3", density = 2, friction = 0.5, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -15.5, -18.5  ,  -373.5, 66.5  ,  -373.5, 15.5  }
                    }
                    
                    
                    
		}
		
		, 
		["floor-4"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "floor-4", density = 2, friction = 0.5, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -200.5, -61  ,  -66.5, -15  ,  -383.5, 67  ,  -383.5, -67  }
                    }
                     ,
                    {
                    pe_fixture_id = "floor-4", density = 2, friction = 0.5, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   383.5, 67  ,  54.5, -1  ,  383.5, 4  }
                    }
                     ,
                    {
                    pe_fixture_id = "floor-4", density = 2, friction = 0.5, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -66.5, -15  ,  54.5, -1  ,  383.5, 67  ,  -383.5, 67  }
                    }
                    
                    
                    
		}
		
		, 
		["floor-5"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "floor-5", density = 2, friction = 0.5, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   322.5, 53.5  ,  67.5, -23.5  ,  177.5, -51.5  ,  322.5, -53.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "floor-5", density = 2, friction = 0.5, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -322.5, 53.5  ,  -322.5, -8.5  ,  67.5, -23.5  ,  322.5, 53.5  }
                    }
                    
                    
                    
		}
		
		, 
		["floor-6"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "floor-6", density = 2, friction = 0.5, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -28.5, 311.5  ,  -28.5, -311.5  ,  28.5, -311.5  ,  28.5, 311.5  }
                    }
                    
                    
                    
		}
		
	} }

        -- apply scale factor
        local s = scale or 1.0
        for bi,body in pairs(physics.data) do
                for fi,fixture in ipairs(body) do
                    if(fixture.shape) then
                        for ci,coordinate in ipairs(fixture.shape) do
                            fixture.shape[ci] = s * coordinate
                        end
                    else
                        fixture.radius = s * fixture.radius
                    end
                end
        end
	
	function physics:get(name)
		return unpack(self.data[name])
	end

	function physics:getFixtureId(name, index)
                return self.data[name][index].pe_fixture_id
	end
	
	return physics;
end

return M

